### ISSUE TITLE
Rocket rust library?

### ISSUE THREAD

**Issue by ogcatt** [tom-draper/api-analytics#13]
Will this api analytics have support for the rocket rust library? It is quite commonly used. Thanks.

**Comment by tom-draper** [comment]
Hi, thanks for the suggestion! Support for Rocket has been on my list of features to include for some time and I'm aiming to get round to it soon. Thanks!

**Comment by ogcatt** [comment]
Neat 🫡

**Comment by tom-draper** [comment]
Analytics for Rust's Rocket web framework are now available with the `rocket-analytics` crate. Thanks!

**Comment by ogcatt** [comment]
Nice!
