### ISSUE TITLE
Remove/Filter Unwanted Endpoints

### ISSUE THREAD

**Issue by Wamy-Dev** [tom-draper/api-analytics#16]
There are certain endpoints I want to hide from my dashboard and the overall requests count. For example, I have a "/status" endpoint that I have an uptime bot ping every 60 seconds and it shows on the dashboard. I don't want the /status endpoint to affect the rest of my analytics. This can also be done for enpoints that have to do with logins to token refreshes, or whatever.

I would like to request that users are able to filter out any number of endpoints and make it not shown on the dashboard at all. But, instead of just deleting them, maybe grey them out instead so I can still see it if I wanted to.

**Comment by tom-draper** [comment]
That's a great idea! I'll try and get that built next week. Thanks a lot :)

**Comment by tom-draper** [comment]
Better late than never! You can now filter out endpoints from the dashboard dataset by clicking the settings cog at the top and entering any paths to hide. It also supports wildcards so /status/* would hide /status/foo/, /status/bar/ and /status/foo/bar/ etc. Thanks for the suggestion
