### ISSUE TITLE
Cannot Pull API Data from Api

### ISSUE THREAD

**Issue by oscarnz** [tom-draper/api-analytics#2]
Hello @tom-draper , just wondering why i cant pull data api as stated in README. 

`response = requests.get("https://api-analytics-server.vercel.app/api/data/", headers=headers)`

It says `{"message":"Invalid API key."}`

**Comment by tom-draper** [comment]
Hi @oscarnz,

Thanks for letting me know about this issue. I believe I've fixed the issue and corrected the readme.

Thanks!

**Comment by oscarnz** [comment]
Thank you!
