### ISSUE TITLE
Doesn't work with flask

### ISSUE THREAD

**Issue by Em1tSan** [tom-draper/api-analytics#23]
I did as in the above example - statistics does not work, is not displayed on the site. There are no errors in the script related to the analytics module. 

On the server based on FastAPI everything works fine.

**Comment by tom-draper** [comment]
Hi, thanks for raising this issue. I'll try and fix this as soon as possible. It looks like an issue with a third party library when using flask version 2.3. For the time being, it should work if you downgrade to flask version 2.2.* or less.
Thanks again

**Comment by tom-draper** [comment]
Thanks for your help, upgrading to `api-analytics==1.1.5` should fix the issue with flask 2.3 and greater
