### ISSUE TITLE
Dashboard is not loading the data

### ISSUE THREAD

**Issue by YuvrajRaghuvanshiS** [tom-draper/api-analytics#29]
Hi Tom,

Firstly, I want to express my gratitude for your project, it has proven to be quite valuable to my team. However, I'm facing an issue over the past few days regarding the dashboard not displaying data.

Upon inspecting the network activity, I observe that all the necessary data is being loaded as expected. So, I suspect that the recent commits made to tweak the dashboard might be the root cause of this problem.

Also, the analysis data, from the following endpoint `https://www.apianalytics-server.com/api/requests/<secret-key>`, is loading correctly and has a size of around 2-3MB. So, the issue doesn't seem to originate from there.

If there's any specific information or action required from my end to assist in resolving this matter, please let me know. I appreciate your help and the work you've put into this project.

Thanks once again.

![image](https://github.com/tom-draper/api-analytics/assets/52948878/581e3df6-c1b1-4075-be88-77740123efab)

**Comment by YuvrajRaghuvanshiS** [comment]
This is what I found in the console
![image](https://github.com/tom-draper/api-analytics/assets/52948878/4c4b951b-650c-42cb-aacf-55b501f0e7f4)

**Comment by tom-draper** [comment]
Hi there, thanks for letting me know! I think the build may have failed, I've rolled back for the time being so it should be working again now. If you clear the cache with Ctrl+F5 it should show your data.
