### ISSUE TITLE
All time users changed to 0 even though it had over 100k users before.

### ISSUE THREAD

**Issue by Snailedlt** [tom-draper/api-analytics#35]
All time users changed to 0 even though it had over 100k users before.
Before:
![image](https://github.com/tom-draper/api-analytics/assets/43886029/54724c05-774f-496f-a882-a535da1aa2eb)

After:
![image](https://github.com/tom-draper/api-analytics/assets/43886029/99c3ebd2-04cd-4fff-9bef-fa7519055c9d)

The response time graph also looks a bit odd now

Link to analytics: https://www.apianalytics.dev/dashboard/fb1f330ea13b4f4c91a8de83895e56e3

**Comment by tom-draper** [comment]
Thanks for raising this. That should be fixed now.
The weird response time graph is likely due to a single extremely high response time data point. I'll see if I can improve the visuals on this.
