### ISSUE TITLE
No requests logged for a long time

### ISSUE THREAD

**Issue by rust-kotlin** [tom-draper/api-analytics#36]
Hi, bro, I am using this library to monitor my axum app, I think I add this middleware layer to my main router rightly and send requests to my web app, but it seemed that it keeps finding no requests.  

So does this logging has some update intervals such as every day that I can't see the recording instantly? Hoping for your reply!

**Comment by rust-kotlin** [comment]
It seemed that this is due to the lack of ip, which is set to be empty String.

**Comment by tom-draper** [comment]
Thanks for raising this, it should be corrected now. There was an integer overflow error on the server when unique user agents were being submitted. It looks unlikely to be related to an empty ip address. Are you able to confirm it's working as you expect now?

**Comment by rust-kotlin** [comment]
Yeah, Thanks! Actually I found that it was due to the user agent six hours ago. Because my user agent is from WeChat Mini Program, it might be somewhat special . When I give a default chrome user agent, it worked for me. I will test your modifications when I am free.

**Comment by rust-kotlin** [comment]
Hi, there! The dashborad loading circle keeps for minutes untill the charts display! Is this some server side error?

**Comment by chalex-eth** [comment]
Hey @tom-draper,
Thanks for your amazing tool, I wanted to give a try, I implement the analytics on an axum project, however I do not have any data into the dashboard or the api.
Is there any latency to expect ? Or did I do something wrong ? 
Thank you

**Comment by tom-draper** [comment]
It should just be a 60 second delay before they appear in the dashboard, and your API will need to have been receiving requests for at least two minutes. I'd also double check your API key is being correctly passed as a parameter. Let us know if it remains an issue and I'll look into it

**Comment by chalex-eth** [comment]
Thank you for responding quickly.
Here is my api key and how I use it.
 
```
let app = Router::new()
        .layer(Analytics::new(String::from(
            "0545b867-45b2-44c6-9c2d-7269a0ec5e12",
        )))
....
```

**Comment by loremaps** [comment]
@tom-draper thanks for this tool. 

We also do not see any data on the dashboard (we are using fastify integration). No errors, just to data. 
Using the API `https://apianalytics-server.com/api/data`, we get back and empty array.

Thanks!

**Comment by tom-draper** [comment]
@chalex-eth It doesn't look as though your logged requests are reaching the server. Are you able to check whether there is an issue sending requests from your APIs environment?

I'll have a look at these issues as soon as possible, although I'm on holiday at the moment so I may be a few days

**Comment by chalex-eth** [comment]
@tom-draper Thanks for the response, any idea how to try to debug to check if requests are sent ?

**Comment by tom-draper** [comment]
@loremaps This issue should be fixed if you upgrade `node-api-analytics` to `>=1.2.2`, thanks

**Comment by loremaps** [comment]
@tom-draper thank you, it works now!
