### ISSUE TITLE
Terms of service & Privacy policy?

### ISSUE THREAD

**Issue by Boscop** [tom-draper/api-analytics#47]
I like the premise of this crate and thanks for making it, it seems very useful as a drop-in solution for full-stack Rust apps 🙂

But: Your website doesn't appear very trustworthy (to someone who doesn't know you), there is no terms of service or privacy policy (or at least a FAQ), and there is no contact info / info about what kind of legal entity is operating this service.

Where are you storing clients' data, and how long, and how is it secured? 

And it seems free to use, how are you funding this? 🙂

I'd try this for my hobby project, but for someone considering to use it in production, it would make sense to answer these questions in a FAQ on the site and add TOS & privacy policy.

**Comment by tom-draper** [comment]
Thank you, these are all very good points! A lot of these are answered in the repo readme, but it would be worth adding to the website to make it clear to anybody who finds it through that route.
I'll make adding a FAQ, TOS, privacy policy and contact info to the website a priority.
The project is fully GDPR compliant and fully funded by myself as a hobby project (although running costs are relatively minimal).
Self-hosting for the backend should be ready within the next two weeks, which will allow users to run the project themselves and have full control over any requests they have logged.
Thanks again

**Comment by Boscop** [comment]
Wow, nice, looking forward to the self hosting ability :)

**Comment by Deepak-du** [comment]
hey @tom-draper is Self-hosting is ready?

**Comment by tom-draper** [comment]
@Deepak-du Self-hosting is now merged. You can get started with the guide <a href="https://github.com/tom-draper/api-analytics/tree/main/server/self-hosting">here</a>. Feel free to give it a go and let me know if you run into any issues.

**Comment by tom-draper** [comment]
Closing this issue as a detailed FAQ and privacy policy now on the website home page, and linked to in the repo readme! I'll continue to keep it up-to-date
