### ISSUE TITLE
Status code is captured before the route handler

### ISSUE THREAD

**Issue by loremaps** [tom-draper/api-analytics#49]
We are using `fastify.addHook("onRequest", fastifyAnalytics(apiKey))` to register and looking at the code:

https://github.com/tom-draper/api-analytics/blob/0308b8468e9e43b9ab46f354ff248ce6d7ba4156/analytics/nodejs/analytics.js#L192

we see that the status will be captured before the route handler is executed. Therefore if a route replies e.g. `404` using `reply.code(404)`, the request will be captured as `200`. 

Is this the intended behavior?

**Comment by tom-draper** [comment]
Thanks for raising this, this has now been patched in the `1.3.0` release. You will need to update your code to add the middleware like the following:

```js
import fastify from 'Fastify';
import { useFastifyAnalytics } from 'node-api-analytics';

const fastify = Fastify();

useFastifyAnalytics(fastify, apiKey);
```
