### ISSUE TITLE
Dashboard does not load

### ISSUE THREAD

**Issue by 1FriendlyDoge** [tom-draper/api-analytics#9]
Whenever I try to go to the analytics dashboard it is stuck on an infinite loading screen.
This is the snippet for loading the middleware (using FastAPI) `app.add_middleware(Analytics, api_key="MY-API-KEY")`.
By looking at devtools I can see that `https://api-analytics-server.vercel.app/api/requests/id-is-here` always returns `{"message":"Invalid user ID.","status":400}`. Am I doing anything wrong or is this an issue with the package?

**Comment by tom-draper** [comment]
Apologies about this, I'm having problems with hosting and currently migrating provider. I should get the service up and running again within the next few days.

**Comment by tom-draper** [comment]
Sorry about the delay. The problem should be solved but an upgrade to the latest Python package will be required.
